import type { Challenge } from '../types';

export const CHALLENGES: Challenge[] = [
  {
    id: 'c1',
    title: 'Touch Grass',
    description: '10 dakika dışarı çık, sadece gözlemle.',
    xp: 50,
    duration: 10,
    icon: '🌿',
    category: 'outdoor',
    completed: false,
  },
  {
    id: 'c2',
    title: 'Hidrasyon Molası',
    description: 'Şu an bir bardak su iç. Dur ve fark et.',
    xp: 20,
    duration: 2,
    icon: '💧',
    category: 'health',
    completed: false,
  },
  {
    id: 'c3',
    title: '5 Sayfa Oku',
    description: 'Herhangi bir kitabın 5 sayfasını oku.',
    xp: 60,
    duration: 15,
    icon: '📖',
    category: 'focus',
    completed: false,
  },
  {
    id: 'c4',
    title: 'Kulaklıksız Yürüyüş',
    description: '15 dakika yürü, sadece dünyayı dinle.',
    xp: 80,
    duration: 15,
    icon: '🚶',
    category: 'outdoor',
    completed: false,
  },
  {
    id: 'c5',
    title: 'Sessiz 2 Dakika',
    description: 'Gözleri kapat, 2 dakika sessizce otur.',
    xp: 40,
    duration: 2,
    icon: '🧘',
    category: 'mindfulness',
    completed: false,
  },
  {
    id: 'c6',
    title: 'Gün Batımı',
    description: 'Gün batımını telefonsuz izle.',
    xp: 100,
    duration: 20,
    icon: '🌅',
    category: 'mindfulness',
    completed: false,
  },
  {
    id: 'c7',
    title: 'Dijital Detoks Saati',
    description: 'Bir saat boyunca telefonu bırak.',
    xp: 150,
    duration: 60,
    icon: '📵',
    category: 'focus',
    completed: false,
  },
  {
    id: 'c8',
    title: 'Yabancı Kelime',
    description: "Duolingo'dan 5 yeni kelime öğren.",
    xp: 70,
    duration: 10,
    icon: '🌍',
    category: 'focus',
    completed: false,
  },
  {
    id: 'c9',
    title: 'Şınav Molası',
    description: '10 şınav çek. Şimdi.',
    xp: 45,
    duration: 3,
    icon: '💪',
    category: 'health',
    completed: false,
  },
  {
    id: 'c10',
    title: 'Arkadaşını Ara',
    description: 'DM değil, gerçekten ara. Sesini duysun.',
    xp: 90,
    duration: 10,
    icon: '📞',
    category: 'social',
    completed: false,
  },
];
